cart/urls.py
from django.urls import path
from . import views

urlpatterns= [
    path('', views.cart, name="cart"),
    path('cart_add/<uuid:fooditem_id>/', views.cart_add, name="cart_add"),
    path('cart_delete/<int:cartitem_id>/', views.cart_delete, name="cart_delete"),
    path('cart_update/<int:cartitem_id>/<int:quantity>/', views.cart_update, name="cart_update"),
    path('checkout/', views.checkout, name="checkout"),
    path('payment/', views.payment, name="payment"),
    path('placeorder/', views.placeorder, name="placeorder"),
]

dishdash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('cart/', include('cart.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
import uuid
from core.models import Fooditem  
from core.models import Customer  



class Cart(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    ]

    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')

    def __str__(self):
        return f'Cart {self.id} by {self.customer.firstname}'

    

    

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    fooditem = models.ForeignKey(Fooditem, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} x {self.fooditem.name}'

    def get_price(self):
        return self.quantity * self.fooditem.price




class Order(models.Model):
    orderstatus = [
        ('Pending', 'Pending'),
        ('Completed', 'Completed'),
        ('Shipping', 'Shipping'),
        ('Cancelled', 'Cancelled'),
    ]
    paymentmode = [
        ('POD', 'POD'),
        ('Paystack', 'Paystack'),
    ]
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    fname = models.CharField(max_length=200, null=False)
    lname = models.CharField(max_length=200, null=False)
    order_email = models.EmailField(max_length=200, null=False)
    order_number = models.CharField(max_length=40, null=False)
    order_address = models.TextField(max_length=800, null=False)
    state = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    order_total = models.IntegerField(null=False)
    payment_mode = models.CharField(max_length=250, choices=paymentmode, null=False)
    payment_id = models.CharField(max_length=250, null=True)
    order_status = models.CharField(max_length=200, choices=orderstatus, default= 'Pending' )
    tracking_number = models.CharField(max_length=250, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Order {self.id} with {self.tracking_number}'

    

    

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    fooditem = models.ForeignKey(Fooditem, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.IntegerField(null=False)

    def __str__(self):
        return f'{self.quantity} x {self.fooditem.name}'

    def get_price(self):
        return self.quantity * self.fooditem.price

cart/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Cart,CartItem,Order,OrderItem
from core.models import Fooditem,Customer,Category
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages, auth
import random

# Create your views here.
def cart_add(request, fooditem_id):
    fooditem = get_object_or_404(Fooditem, id=fooditem_id)
    cart, created = Cart.objects.get_or_create(customer=request.user, status='pending')

    cartitem, created = CartItem.objects.get_or_create(cart=cart, fooditem=fooditem)
    
    if not created:
        cartitem.quantity += 1
        cartitem.save()

    return redirect(request.META.get('HTTP_REFERER', '/'))


@login_required(login_url='login')
def cart(request):
    categories = Category.objects.all()
    cart, created = Cart.objects.get_or_create(customer=request.user, status='pending')
    cartitems = cart.cartitem_set.all()
    total_price = sum(
        item.quantity * (item.fooditem.off_price if item.fooditem.off_price else item.fooditem.price)for item in cartitems )    
    context = {'cart': cart, 'cartitems': cartitems, 'total_price':total_price, 'categories': categories}

    return render(request, 'cart/cart.html', context)
 


def cart_update(request, cartitem_id, quantity):
    cartitem = get_object_or_404(CartItem, id=cartitem_id, cart__customer=request.user, cart__status='pending')
    
    if quantity > 0:
        cartitem.quantity = quantity
        cartitem.save()
    else:
        cartitem.delete()  
    
    return redirect('cart') 

def cart_delete(request, cartitem_id):
    cartitem = get_object_or_404(CartItem, id=cartitem_id, cart__customer=request.user, cart__status='pending')
    cartitem.delete()
    
    return redirect('cart')

@login_required(login_url='login')
def checkout(request):
    categories = Category.objects.all()
    cart, created = Cart.objects.get_or_create(customer=request.user, status='pending')
    cartitems = cart.cartitem_set.all()
    total_price = sum(
        item.quantity * (item.fooditem.off_price if item.fooditem.off_price else item.fooditem.price)for item in cartitems )    
    userprofile = Customer.objects.filter(id=request.user.id).first()
    context = {'cart': cart, 'cartitems': cartitems, 'total_price':total_price,'userprofile':userprofile, 'categories':categories}

    return render(request, 'cart/checkout.html', context)



@login_required(login_url='login')
def placeorder(request):
    if request.method == 'POST':

        currentuser=Customer.objects.filter(id=request.user.id).first()

        if not currentuser.firstname :
            currentuser.firstname = request.POST.get('fname')
            currentuser.lastname = request.POST.get('lname')
            currentuser.phone_number = request.POST.get('order_number')
            currentuser.email = request.POST.get('order_email')
            currentuser.address = request.POST.get('order_address')
            currentuser.save()

        neworder = Order()
        neworder.customer = request.user
        neworder.fname = request.POST.get('fname')
        neworder.lname = request.POST.get('lname')
        neworder.order_number = request.POST.get('order_number')
        neworder.order_email = request.POST.get('order_email')
        neworder.order_address = request.POST.get('order_address')
        neworder.state = request.POST.get('state')
        neworder.city = request.POST.get('city')

        cart = get_object_or_404(Cart, customer=request.user, status='pending')
        cartitems = cart.cartitem_set.all()

        neworder.order_total = sum(item.quantity * item.fooditem.price for item in cartitems)

        track_num = 'dishdash' + str(random.randint(1111111, 9999999))
        while Order.objects.filter(tracking_number=track_num).exists():
            track_num = 'dishdash' + str(random.randint(1111111, 9999999))
        neworder.tracking_number = track_num

        neworder.save()
        request.session['current_order'] = neworder.id

        for item in cartitems:
            OrderItem.objects.create(
                order=neworder,
                fooditem=item.fooditem,
                quantity=item.quantity,
                price=item.fooditem.price
            )

        cart.status = 'completed'
        # cart.cartitem_set.all().delete()
        cart.save()

        messages.success(request, 'Your Order Has Been Placed')

        return redirect('payment')

    return redirect('cart')

@login_required(login_url='login')
def payment(request):
    categories = Category.objects.all()
    cart, created = Cart.objects.get_or_create(customer=request.user, status='pending')
    cartitems = cart.cartitem_set.all()
    userprofile = Customer.objects.filter(id=request.user.id).first()
   
    current_order_id = request.session.get('current_order')
    current_order = Order.objects.get(id=current_order_id)

    total_price = current_order.order_total

    context = {
        'cart': cart, 
        'cartitems': cartitems, 
        'total_price':total_price,
        'userprofile':userprofile, 
        'categories':categories,
        'current_order':current_order}

    if request.method == 'POST':
        payment_mode = request.POST.get('payment_mode')

        current_order.payment_mode = payment_mode
        current_order.save()

        del request.session['current_order']

        messages.success(request, 'Payment Successful')
        return redirect('index')
    
   
    return render(request, 'cart/payment.html', context)

theme/templates/cart/cart.html
{% extends 'base.html' %} 
{% load static %}
{% load humanize %}
{% block title%} | Cart {% endblock %}
{% block content %}



<div class="bg-white min-h-min">
    <div class="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mt-8 py-7">
        <div class="grid gap-4">
            <div class="flex justify-start gap-5 list-none w-full font-nova py-7 pl-7">
                <li class="self-center hover:font-bold"><a href="{% url 'index' %}">Home</a></li>
                <li class="self-center hover:font-bold"><a href="{% url 'categories' %}">Categories</a></li>
            {% if fooditem %}
                {% for fooditem in fooditem %}
                    <li class="self-center hover:font-bold"><a href="{% url 'fooditem' fooditem.id %}">{{ fooditem.name }}</a></li>
                {% endfor %}
            {% endif %}
            </div> 
            <h3 class="font-nova text-2xl pl-7">Cart</h3>

            <hr class="text-gray-700 w-full">


            {% if cartitems %}
                {% for cartitem in cartitems %}
                    <div>
                        <div class="grid grid-cols-1 py-6 md:grid-cols-[1fr_2fr] pl-7 gap-12 items-center justify-items-center">
                            <img class="w-56 h-52 rounded-lg" src="{{ cartitem.fooditem.image.url }}" alt="">
                            <div class="grid grid-cols-4 gap-5 items-center justify-items-center">
                                <h3 class="font-fjord text-xl font-semibold">{{ cartitem.fooditem.name }}</h3>
                                <div class="flex justify-center items-center p-3 gap-3 h-10 border border-gray-300 rounded-lg shadow-2xl">
                                    <a href="{% url 'cart_update' cartitem.id cartitem.quantity|add:-1 %}">-</a>
                                    <span class="text-lg font-semibold">{{ cartitem.quantity }}</span>
                                    <a href="{% url 'cart_update' cartitem.id cartitem.quantity|add:1 %}">+</a>
                                </div>
                                {% if cartitem.fooditem.off_price %}
                                    <h3 class="font-fjord font-semibold text-orange-500">&#8358; {{ cartitem.fooditem.off_price|intcomma }}</h3>
                                {% else %}
                                    <h3 class="self-center font-fjord">&#8358; {{ cartitem.fooditem.price |intcomma }}</h3>
                                {% endif %}
                                <a href="{% url 'cart_delete' cartitem.id %}">
                                    <i class="fas fa-trash-alt fa-lg" style="color: #ffa500;"></i>     
                                </a>
                            </div>
                        </div>
                        <hr class="text-gray-700 w-full">
                    </div>
                {% endfor %}
            {% endif %}

        </div>


        <div class="pt-24 px-3">
            <div class="grid justify-items-start w-full mb-8">
                <h3 class="font-nova text-xl justify-center font-semibold">Checkout</h3>
            </div>
            
            <div class="grid grid-cols-[3fr_1fr_1fr] mt-4 text-center justify-items-center">
                <h3>Orders</h3>
                <h3>Quantity</h3>
                <h3>Price</h3>
            </div>
            <hr class="border-gray-500 font-bold w-full">

            <div>
                {% if cartitems %}
                    {% for cartitem in cartitems %}
                        <div class="grid grid-cols-[3fr_1fr_1fr] py-4 text-center justify-items-center">
                            <div class="grid grid-cols-2 gap-3 w-full">
                                <img class="w-20 h-12" src="{{ cartitem.fooditem.image.url }}" alt="">
                                <h3 class="self-center font-fjord">{{ cartitem.fooditem.name }}</h3>
                            </div>
                            <h3 class="self-center font-fjord">{{ cartitem.quantity }}</h3>
                            {% if cartitem.fooditem.off_price %}
                                <h3 class="font-fjord font-semibold text-orange-500">&#8358; {{ cartitem.fooditem.off_price|intcomma }}</h3>
                            {% else %}
                                <h3 class="self-center font-fjord">&#8358; {{ cartitem.fooditem.price |intcomma }}</h3>
                            {% endif %}
                        </div>
                        <hr class="text-gray-700 w-full">
                    {% endfor %}
                {% endif %}
                
            </div>

            <div class="grid grid-cols-2 py-4">
                <h3 class="self-center justify-self-start font-fjord font-semibold">Grand Total</h3>
                <h3 class="self-center font-fjord justify-self-end font-semibold">&#8358; {{ total_price | intcomma }}</h3>
            </div>
            <div class="flex p-4 justify-center">
                <a class="font-fjord p-3 text-white bg-orange-500 rounded-lg hover:bg-orange-600 self-center" href="{% url 'checkout' %}">Checkout</a>
            </div>
        </div>
        
    </div>


</div>

{% endblock content %}

theme/templates/cart/checkout.html
{% extends 'base.html' %} 
{% load static %}
{% load humanize %}
{% block title%} | Checkout{% endblock %}
{% block content %}


<div class="bg-white overflow-hidden min-h-min">
    <div class="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4">
        <div>
            <div class=" mt-10 p-4">
                <form action="{% url 'placeorder' %}" method="post" class="grid p-6 rounded-lg shadow-md font-fjord">
                    {% csrf_token %}
                    <div class=" flex text-center justify-center font-fjord mb-10">
                        <h3 class="text-xl font-semibold">Shipping Details</h3>
                    </div>
                    <div class="grid grid-cols-2 gap-4 mb-4">
                        <div class="flex flex-col">
                            <label for="fname" class="mb-2 text-black font-semibold">First Name</label>
                            <input type="text" name="fname" value="{{ userprofile.firstname }}" required class="p-2 border border-black rounded focus:outline-none focus:border-orange-500">
                        </div>
                        <div class="flex flex-col">
                            <label for="lname" class="mb-2 text-black font-semibold">Last Name</label>
                            <input type="text" name="lname" value="{{ userprofile.lastname }}" required class="p-2 border border-black rounded focus:outline-none focus:border-orange-500">
                        </div>
                    </div>
                    
                    <div class="grid grid-cols-2 gap-4 mb-4">
                        <div class="flex flex-col">
                            <label for="order_number" class="mb-2 text-black font-semibold">Phone Number</label>
                            <input type="tel" name="order_number" value="{{ userprofile.phone_number }}" required class="p-2 border border-black rounded focus:outline-none focus:border-orange-500">
                        </div>
                        <div class="flex flex-col">
                            <label for="order_email" class="mb-2 text-black font-semibold">Email</label>
                            <input type="email" name="order_email" value="{{ userprofile.email }}" required class="p-2 border border-black rounded focus:outline-none focus:border-orange-500">
                        </div>
                    </div>
                    
                    <div class="flex flex-col mb-4">
                        <label for="order_address" class="mb-2 text-black font-semibold">Address</label>
                        <input type="text" name="order_address" value="{{ userprofile.address }}" required class="p-2 border border-black rounded focus:outline-none focus:border-orange-500">
                    </div>
                    
                    <div class="grid grid-cols-2 gap-4 mb-4">
                        <div class="flex flex-col">
                            <label for="state" class="mb-2 text-black font-semibold">State</label>
                            <input type="text" name="state" required class="p-2 border border-black rounded focus:outline-none focus:border-orange-500">
                        </div>
                        <div class="flex flex-col">
                            <label for="city" class="mb-2 text-black font-semibold">City</label>
                            <input type="text" name="city" required class="p-2 border border-black rounded focus:outline-none focus:border-orange-500">
                        </div>
                    </div>
                    
                    
                    <button type="submit" class=" justify-self-center p-2 w-1/4 mt-4 text-white bg-orange-600 rounded hover:bg-orange-700 ">
                        Submit
                    </button> 
                    
                </form>
                
                
                
            </div>
        </div>

        <div class="pt-24 px-3">
            <div class="grid justify-items-start w-full mb-8">
                <h3 class="font-nova text-xl justify-center">Order Summary</h3>
            </div>
            
            <div class="grid grid-cols-[3fr_1fr_1fr] mt-4 text-center justify-items-center">
                <h3>Orders</h3>
                <h3>Quantity</h3>
                <h3>Price</h3>
            </div>
            <hr class="border-gray-500 font-bold w-full">

            <div>
                {% if cartitems %}
                    {% for cartitem in cartitems %}
                        <div class="grid grid-cols-[3fr_1fr_1fr] py-4 text-center justify-items-center">
                            <div class="grid grid-cols-2 gap-3 w-full">
                                <img class="w-20 h-12" src="{{ cartitem.fooditem.image.url }}" alt="">
                                <h3 class="self-center font-fjord">{{ cartitem.fooditem.name }}</h3>
                            </div>
                            <h3 class="self-center font-fjord">{{ cartitem.quantity }}</h3>
                            {% if cartitem.fooditem.off_price %}
                                <h3 class="font-fjord font-semibold text-orange-500">&#8358; {{ cartitem.fooditem.off_price|intcomma }}</h3>
                            {% else %}
                                <h3 class="self-center font-fjord">&#8358; {{ cartitem.fooditem.price |intcomma }}</h3>
                            {% endif %}
                        </div>
                        <hr class="text-gray-700 w-full">
                    {% endfor %}
                {% endif %}
                
            </div>

            <div class="grid grid-cols-2 py-4">
                <h3 class="self-center justify-self-start font-fjord font-semibold">Grand Total</h3>
                <h3 class="self-center font-fjord justify-self-end font-semibold">&#8358; {{ total_price | intcomma }}</h3>
            </div>
            <div class="flex p-4 justify-center">
                <a class="font-fjord text-white p-3 bg-orange-500 rounded-lg hover:bg-orange-600 self-center" href="{% url 'cart' %}">Go Back To Cart</a>
            </div>
           
        </div>
       

       
    </div>

   

</div>


{% endblock content %}

theme/templates/cart/payment.html
{% extends 'base.html' %} 
{% load static %}
{% load humanize %}
{% block title%} | Payment{% endblock %}
{% block content %}


<div class="bg-white overflow-hidden min-h-min">
    <div class="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4">
        <div class="pt-24 px-3">
            <h3 class="font-nova text-2xl mb-14">Payment Info</h3>
            <h3 class="font-fjord font-semibold justify-self-center mb-8">Payment Method</h3>
            <form method="POST" action="{% url 'payment' %}" class="grid grid-rows-2 justify-items-center gap-3 mb-5">
                {% csrf_token %}
                <input type="hidden" name="payment_mode" id="payment_mode" value="">
                <button type="submit" class="font-fjord bg-orange-500 text-white rounded-2xl p-3 text-center w-1/2 md:w-1/4 hover:bg-orange-600" name="payment_mode" value="POD" >
                    Pay On Delivery <i class="fas fa-hand-holding-usd fa-lg"></i>
                </button>
                <button onclick="makePaystackPayment()" type="button" class="font-fjord bg-orange-500 text-white rounded-2xl p-3 text-center w-1/2 md:w-1/4 hover:bg-orange-600" name="payment_mode" value="Paystack">
                    PayStack <i class="far fa-credit-card fa-lg"></i>
                </button>
            </form>
        </div>

        <div class="pt-24 px-3">
            <div class="grid justify-items-start w-full mb-8">
                <h3 class="font-nova text-xl justify-center">Order Summary</h3>
            </div>
            
            <div class="grid grid-cols-[3fr_1fr_1fr] mt-4 text-center justify-items-center">
                <h3>Orders</h3>
                <h3>Quantity</h3>
                <h3>Price</h3>
            </div>
            <hr class="border-gray-500 font-bold w-full">

            <div>
                {% if current_order.orderitem_set.all %}
                    {% for  orderitem in current_order.orderitem_set.all %}
                        <div class="grid grid-cols-[3fr_1fr_1fr] py-4 text-center justify-items-center">
                            <div class="grid grid-cols-2 gap-3 w-full">
                                <img class="w-20 h-12" src="{{ orderitem.fooditem.image.url }}" alt="">
                                <h3 class="self-center font-fjord">{{ orderitem.fooditem.name }}</h3>
                            </div>
                            <h3 class="self-center font-fjord">{{ orderitem.quantity }}</h3>
                            {% if orderitem.fooditem.off_price %}
                                <h3 class="font-fjord font-semibold text-orange-500">&#8358; {{ orderitem.fooditem.off_price|intcomma }}</h3>
                            {% else %}
                                <h3 class="self-center font-fjord">&#8358; {{ orderitem.fooditem.price |intcomma }}</h3>
                            {% endif %}
                        </div>
                        <hr class="text-gray-700 w-full">
                    {% endfor %}
                {% endif %}
                
            </div>

            <div class="grid grid-cols-2 pt-4 pb-12 ">
                <h3 class="self-center justify-self-start font-fjord font-semibold">Grand Total</h3>
                <h3 class="self-center font-fjord justify-self-end font-semibold">&#8358; {{ total_price | intcomma }}</h3>
            </div>
           
        </div>
    </div>


    <script src="https://js.paystack.co/v2/inline.js"></script>


    <script>
        function makePaystackPayment() {
            const paystack = new PaystackPop();

            paystack.newTransaction({
                key: "pk_live_2aecee82a9657028d5e010f283e938b5d7d3638a",
                email: "{{current_order.order_email}}",
                amount: "{{current_order.order_total}} * 1000",

                onSuccess:(transaction) => {
                    console.log(transaction);
                    window.location.href = "/index/{{current_order.payment_id}}";
                },

                onCancel:() => {
                    Swal.fire({
                        title: "Payment Cancelled",
                        icon: "error",
                    });
                },
            })
        }
    </script>


</div>

{% endblock content %}